import { Router } from "express";
import { AuthRoutes } from "../modules/auth/auth.route";
import { UserRoutes } from "../modules/user/user.route";
import { TeacherRoutes } from "../modules/teacher/teacher.route";
import { SubjectRoutes } from "../modules/subject/subject.route";
import { AdminRoutes } from "../modules/admin/admin.route";
import { ApplicationRoutes } from "../modules/application/application.route";
import { StudentRoutes } from "../modules/student/student.route";
import { TeacherSubjectRoutes } from "../modules/teacherSubject/teacherSubject.route";
import { MediaRoutes } from "../modules/media/media.route";
import { ExamRoutes } from "../modules/exam/exam.route";
import { FromFillupRoutes } from "../modules/fromFillup/fromFillup.route";
import { NoticeRoutes } from "../modules/notice/notice.route";
import { ClassDataRoutes } from "../modules/classData/classData.route";
import { AcademicLevelRoutes } from "../modules/academin_level/academicLevel.route";
import { StatsRoutes } from "../modules/stats/stats.route";
import { ClassTeacherRoutes } from "../modules/classTeacher/classTeacher.route";
import { PaymentRoutes } from "../modules/payment/payment.route";
import { admissionConfigRoutes } from "../modules/admission_config/admissionConfig.route";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/teacher", TeacherRoutes);
router.use("/subject", SubjectRoutes);
router.use("/admin", AdminRoutes);
router.use("/application", ApplicationRoutes);
router.use("/student", StudentRoutes);
router.use("/teacher-subject", TeacherSubjectRoutes);
router.use("/media", MediaRoutes);
router.use("/exams", ExamRoutes);
router.use("/from-fillup", FromFillupRoutes);
router.use("/notices", NoticeRoutes);
router.use("/classes", ClassDataRoutes);
router.use("/academic-level", AcademicLevelRoutes);
router.use("/stats", StatsRoutes);
router.use("/class-teacher", ClassTeacherRoutes);
router.use("/payments", PaymentRoutes);
router.use("/admission-config", admissionConfigRoutes);

export const IndexRoutes = router;
